services:
  mariadb:
    container_name: mariadb
    image: mariadb:11
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MARIADB_ROOT_PASSWORD: password
    ports:
        - 9503:3306
    volumes:
      - ./mariadb-data:/var/lib/mysql
    networks:
        - site
        
  php-fpm:
      container_name: php-fpm
      build: ./docker/php-fpm
      depends_on:
        - mariadb
      environment:
          PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=app}
          XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9000 log=/tmp/xdebug/xdebug.log output_dir=/tmp/xdebug start_with_request=trigger"
          XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      extra_hosts:
            - "host.docker.internal:host-gateway"
      volumes:
        - ./app/:/var/www
      networks:
        - site

  nginx:
      container_name: nginx
      build: ./docker/nginx
      volumes:
        - ./app/:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/sites/:/etc/nginx/sites-available
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        - ./docker/nginx/certs/:/etc/nginx/certs
      depends_on:
        - php-fpm
      ports:
        - "8060:80"
        - "6443:443"
      networks:
        - site

networks:
  site:
